blacksmith-eth/blacksmith

core/database/index.ts, lowdb.d.ts, package.json, yarn.lock
- Upgrade `lowdb` to 5.0.5
- Resolve type import issues
=> deps: upgrade lowdb to 5.0.5

components/contract/manager/index.tsx, components/contract/setup/index.tsx, components/field/index.tsx, components/functions/index.test.tsx, components/inputs/index.tsx, components/wallet/transfer/index.tsx
Prefer named imports from `React` submodules.
Replace all inline usage of `React.*`
=> refactor: replace react import with named imports

components/contract/index.test.tsx
Remove duplication in contract component tests.
Extract `renderContract` test helper function.
Also replaces invalid `0x123` address with `buildAddress` factory function.
=> refactor: extract contract test render function

components/connect/index.tsx, core/chains/index.test.ts, core/chains/index.ts, pages/_app.tsx
The forked chain name should be shown rather than the chain id.
Configure forked `mainnet`, `goerli`, and `sepolia` chains.
Replaces `localhost` chain with `foundry`.
=> feat: configure forked chains

components/contract/index.tsx, components/wallet/account/index.tsx
Prefer named type definitions over inline types.
- Extract `ContractProps` type
- Extract `OptionProps` type
=> refactor: extract inline types

README.md, components/contract/manager/index.tsx, pages/api/contracts/[address].ts
Users should be able to avoid rate limits by providing an Etherscan API key.
Attempt Etherscan API key retrieval from `process.env` on contract address import.
=> feat: etherscan api key

components/contract/index.test.tsx, components/contract/index.tsx, components/contracts/index.test.tsx, core/constants/index.ts, core/utils/index.ts, hooks/useArgs/index.test.tsx, hooks/useArgs/index.ts, hooks/useEther/index.ts, pages/index.tsx, testing/factory/index.ts
Reduce bundle size.
- Use tree shaking imports
- Remove erroneous type imports
- Create local copy of `AddressZero`
=> refactor: reduce bundle size imports

components/contract/manager/index.tsx
React `children` prop should not be spread as button attribute.
Destructure `children` from props.
=> fix: destructure children from props

components/function/output/index.tsx, components/function/pure/index.tsx, components/function/view/index.tsx, core/types/index.ts, testing/factory/index.ts
Improve type checking by replacing `any` usages.
Create a custom `Result` type for contract hook data.
=> refactor: replace any type with result

package.json, yarn.lock
=> deps: upgrade eslint to 8.31.0

package.json, yarn.lock
- Upgrade `@commitlint/cli` to 17.4.0
- Upgrade `@commitlint/config-conventional` to 17.4.0
=> deps: upgrade commitlint to 17.4.0

hooks/useArgs/index.test.tsx
Remove duplication in `useArgs` test suite.
Extract `renderUseArgsHook` test helper function.
Reduces use of the `as AbiParameterWithComponents[]` type assertion.
=> test: extract use args render hook

package.json, yarn.lock
- Upgrade `@commitlint/cli` to 17.4.2
- Upgrade `@commitlint/config-conventional` to 17.4.2
=> deps: upgrade commitlint to 17.4.2

components/connect/index.tsx
Avoid extended markup in components with multiple `return` statements.
Extract markup from each connect button `return` statement into separate components.
=> refactor: extract connect button components

.gitignore, components/function/nonpayable/index.test.tsx, components/function/nonpayable/index.tsx, components/function/payable/index.test.tsx, components/function/payable/index.tsx, components/function/pure/index.test.tsx, components/function/pure/index.tsx, components/function/signature/index.test.tsx, components/function/signature/index.tsx, components/function/view/index.test.tsx, components/function/view/index.tsx
appreciate your patience on this @unholypanda! 🙇 ski season stoke surpassed the dev itch for a little bit there :)
getting a fresh start on [this pr](https://github.com/blacksmith-eth/blacksmith/pull/1) now with the new contrib guidelines and pr template
more complex contracts such as seaport looked a little cluttered once imported
Add a +/- collapse toggle to each function in a contract's ABI. This has the effect of making navigation to a specific method easier for complex ABIs, while sacrificing a little friction for contracts with simpler signatures.
I saw CI will still need to be approved to run, but i've gone through the steps noted in the [contributing doc](https://github.com/blacksmith-eth/blacksmith/blob/930eba71ba23c63d6fb842a2731a3e28064dcc79/.github/CONTRIBUTING.md) and it all …
=> Collapsible functions

components/function/index.tsx, components/function/nonpayable/index.test.tsx, components/function/nonpayable/index.tsx, components/function/payable/index.test.tsx, components/function/payable/index.tsx, components/function/pure/index.test.tsx, components/function/pure/index.tsx, components/function/signature/index.test.tsx, components/function/signature/index.tsx, components/function/view/index.test.tsx, components/function/view/index.tsx
React state that can be toggled should leverage the `useToggle` custom hook.
Replace the React `useState` hook with the `useToggle` hook.
Adding the `initialCollapsed` prop makes for easier testing and will enable a planned feature to configure whether functions are expanded or collapsed by default.
=> refactor: use toggle hook for collapse

package.json, yarn.lock
- Upgrade `vitest` to 0.27.3
- Upgrade `@vitest/coverage-c8` to 0.27.3
=> deps: upgrade vitest to 0.27.3

package.json, yarn.lock
=> deps: upgrade jsdom to 21.1.0

components/functions/index.test.tsx, components/wallet/account/index.test.tsx, components/wallet/index.test.tsx, components/wallet/transfer/index.test.tsx
The jest `Mock` types should be replaced with the vitest `Mock` type.
Replace jest `Mock` types with vitest `Mock` type.
=> refactor: replace jest mock with vitest mock

package.json, yarn.lock
- Upgrade `vitest` to 0.28.2
- Upgrade `@vitest/coverage-c8` to 0.28.2
- Update transitive dependencies
=> deps: upgrade vitest to 0.28.2

package.json, yarn.lock
- Upgrade `vitest` to 0.28.3
- Upgrade `@vitest/coverage-c8` to 0.28.3
- Update transitive dependencies
=> deps: upgrade vitest to 0.28.3

components/contract/index.tsx, components/function/index.tsx, components/function/nonpayable/index.test.tsx, components/function/nonpayable/index.tsx, components/function/payable/index.test.tsx, components/function/payable/index.tsx, components/function/pure/index.test.tsx, components/function/pure/index.tsx, components/function/signature/index.tsx, components/function/view/index.test.tsx, components/function/view/index.tsx, components/functions/index.tsx, core/types/index.ts, testing/factory/index.ts
The `buildAbiDefinedFunction` test helper randomly generates a `stateMutability` value of "nonpayable", "payable", "pure", or "view". This test helper was being used in tests that expect a specific `stateMutability` value without specifying the correct override value to the helper.
Test helpers were added for each of the state mutability function types.
Stricter types were added to components that render ABI functions with a specific state mutability type to help prevent misuse and confusion in tests and production code.
=> test: add function state helpers

package.json, yarn.lock
- Upgrade `@headlessui/react` to 1.7.8
- Update transitive dependencies
=> deps: upgrade @headlessui/react to 1.7.8

components/balance/index.test.tsx, components/contract/index.test.tsx, components/contracts/index.test.tsx, components/field/index.test.tsx, components/function/nonpayable/index.test.tsx, components/function/output/index.test.tsx, components/function/payable/index.test.tsx, components/function/pure/index.test.tsx, components/function/signature/index.test.tsx, components/function/view/index.test.tsx, components/functions/index.test.tsx, components/inputs/index.test.tsx, components/wallet/index.test.tsx, testing/types.ts
Duplicate `Partial<ComponentProps<typeof *>>` should be extracted into a custom type.
Add a custom `PartialProps` type.
=> test: add partial prop type helper

testing/factory/index.ts
Specific generated words in tests cause erroneous failures. This is due to there being multiple matches for a given word when only one instance of the word is expected.
- Add unique reserved word faker helpers – `adjective`, `noun`, and `verb`
- Add "unit" to reserved word list
=> test: add unique reserved word faker helpers

package.json
Blacksmith should include a way for tests to easily be run in watch mode.
Add script for running tests in watch mode.
=> chore: add test watch script

package.json, yarn.lock
=> deps: upgrade typescript to 4.9.5

components/function/index.test.tsx, components/function/nonpayable/index.test.tsx, components/function/payable/index.test.tsx, components/function/pure/index.test.tsx, components/function/view/index.test.tsx
Inexact matchers cause erroneous test failures due to partial matches on generated text.
Replace some test assertions that depend on `exact: false`.
=> test: enforce exact text match

README.md
The arguments needed to import contracts into Blacksmith via `forge script` deviate from that of `forge create`. This should be documented.
Add an example for importing contracts via `forge script`.
=> docs: add forge script import example

__tests__/pages/api/verify.test.ts, package.json, pages/api/verify.ts, yarn.lock
Verify check requests with missing/mistyped data payloads should return a 400 status code with helpful error messaging.
Add request schema validation to verify check handler.
- Add `zod-validation-error`
- Add `fp-ts`
=> feat: check verify schema validation

__tests__/pages/api/verify.test.ts, pages/api/verify.ts
Verify requests with missing/mistyped data payloads should return a 400 status code with helpful error messaging.
Add request schema validation to verify handler.
=> feat: add verify request parser

package.json, yarn.lock
Upgrade `tailwindcss` to 3.2.6
=> deps: upgrade tailwindcss to 3.2.6

.eslintrc.json, package.json, yarn.lock
Identify more potential code issues with extended ESLint rules.
Extend ESLint to include `eslint:recommended`, `plugin:@typescript-eslint/recommended`, and `prettier`.
Temporarily ignore `@typescript-eslint/ban-types`, `@typescript-eslint/no-explicit-any`,  and`@typescript-eslint/no-non-null-assertion` rules until they are addressed.
=> deps: extend eslint

package.json, yarn.lock
- Upgrade `@typescript-eslint/parser` to 5.52.0
- Upgrade `@typescript-eslint/eslint-plugin` to 5.52.0
=> deps: upgrade @typescript-eslint to 5.52.0

package.json, yarn.lock
Upgrade `tailwindcss` to 3.2.7
=> deps: upgrade tailwindcss to 3.2.7

__tests__/pages/api/verify.test.ts, pages/api/verify.ts
#187
Transform the provided contract address to be the checksummed address on verification.
=> fix: remove contract by address

.eslintrc.json, components/button/index.tsx, components/function/container/index.tsx
The `@typescript-eslint/ban-types` lint rule should be enforced.
Replace instances of type `{}` with `Record<string, any>`.
=> refactor: remove ignore ban types rule

package.json, yarn.lock
- Upgrade `@typescript-eslint/eslint-plugin` to 5.53.0
- Upgrade `@typescript-eslint/parser` to 5.53.0
=> deps: upgrade @typescript-eslint to 5.53.0

testing/factory/index.ts
Avoid calling `hasOwnProperty` from an object directly to prevent subtle bugs.
Create a `hasProperty` helper that uses `Object.prototype.hasOwnProperty.call(obj, prop)` in place of `obj.hasOwnProperty(prop)`.
More information can be found here: https://eslint.org/docs/latest/rules/no-prototype-builtins
=> refactor: call object prototype property predicate

package.json, yarn.lock
Upgrade `next-router-mock` to 0.9.2
=> deps: upgrade next-router-mock to 0.9.2

hooks/useContracts/index.test.tsx
Remove instances of banned type `{}`.
Replace `{}` type with `Record<string, any>`
Need to investigate why ESLint isn't identifying this since it is considered a banned type.
=> refactor: replace empty object with record type

__tests__/pages/api/verify.test.ts, package.json, yarn.lock
- Upgrade `zod-validation-error` to 1.0.1
- Update error message assertions to conform with new zod API
- Remove erroneous async/await usage in `__tests__/pages/api/verify.test.ts`
=> deps: upgrade zod-validation-error to 1.0.1

package.json, yarn.lock
=> deps: upgrade eslint to 8.36.0

README.md
Blacksmith users have noted `forge 0.2.0 (d1c84e3 2023-03-13T00:05:05.333096Z)` does not seem to recognize the `--etherscan-api-key` being specified in command line arguments.
Add documentation for a workaround solution that sets the fake Etherscan API Key for Blacksmith in `foundry.toml`.
=> docs: add etherscan api key workaround

package.json, yarn.lock
Upgrade `node-mocks-http` to 1.12.2
=> deps: upgrade node-mocks-http to 1.12.2

package.json, yarn.lock
=> deps: upgrade typescript to 5.0.2

testing/factory/index.ts
Specific generated words in tests cause erroneous failures. This is due to there being multiple matches for a given word when only one instance of the word is expected.
Add "void" to reserved word list
=> test: add void to reserved words

components/function/index.test.tsx, components/function/index.tsx, components/functions/index.tsx
Avoid shadowing the built-in `Function`.
Rename `Function` component to `Func`
=> refactor: remove function shadow

components/introduction/manager/index.test.tsx, components/introduction/manager/index.tsx, components/introduction/setup/index.tsx
Template strings should only be used when necessary.
Replace template strings without interpolated values with double quotes.
=> style: avoid unnecessary template stings

package.json, yarn.lock
Upgrade `next-router-mock` to 0.9.3
=> deps: upgrade next-router-mock to 0.9.3

package.json, yarn.lock
- Upgrade `@typescript-eslint/eslint-plugin` to 5.56.0
- Upgrade `@typescript-eslint/parser` to 5.56.0
=> deps: upgrade @typescript-eslint to 5.56.0

package.json, yarn.lock
- Upgrade `@typescript-eslint/eslint-plugin` to 5.57.1
- Upgrade `@typescript-eslint/parser` to 5.57.1
=> deps: upgrade @typescript-eslint to 5.57.1

package.json, yarn.lock
=> deps: upgrade eslint to 8.38.0

package.json, yarn.lock
Upgrade `@commitlint/config-conventional` to 17.6.1
=> deps: upgrade config-conventional to 17.6.1

package.json, yarn.lock
- Upgrade `@typescript-eslint/eslint-plugin` to 5.59.0
- Upgrade `@typescript-eslint/parser` to 5.59.0
=> deps: upgrade @typescript-eslint to 5.59.0

package.json, yarn.lock
Upgrade `tailwindcss` to 3.3.2
=> deps: upgrade tailwindcss to 3.3.2

package.json, yarn.lock
- Upgrade `@typescript-eslint/eslint-plugin` to 5.59.7
- Upgrade `@typescript-eslint/parser` to 5.59.7
=> deps: upgrade @typescript-eslint to 5.59.7

package.json, yarn.lock
- Upgrade `@typescript-eslint/eslint-plugin` to 5.59.8
- Upgrade `@typescript-eslint/parser` to 5.59.8
=> deps: upgrade @typescript-eslint to 5.59.8

README.md
Blacksmith contract verification/import is failing on recent versions of Foundry.
Add a workaround to the README.
=> docs: foundry workaround

README.md
When trying to install the latest version of blacksmith I found out that the package installation line was not finished
I added the install command to install the packages !
@unholypanda
=> fix(docs): add a install package command

components/field/index.test.tsx, hooks/useArgs/index.test.tsx, hooks/useEther/index.test.tsx, package.json, pnpm-lock.yaml, testing/factory/index.ts
Upgrade `@faker-js/faker` to 8.0.2
Removes uniqueness constraint on randomly generated text which may reintroduce test flakiness. This is intentional. The tests should be more robust and not need to depend on uniquely generated text.
=> deps: upgrade @faker-js/faker to 8.0.2

package.json
Enables tests to run properly with node versions above v16.X.X.
Disable the experimental fetch, which `msw` does not yet support.
=> chore: disable experimental fetch in test scripts

components/field/index.test.tsx, components/function/nonpayable/index.test.tsx, components/function/payable/index.test.tsx, components/function/pure/index.test.tsx, components/function/view/index.test.tsx, components/introduction/manager/index.test.tsx, components/introduction/manager/index.tsx, components/introduction/setup/index.test.tsx, components/wallet/transfer/index.test.tsx
- Use userEvent `click` and `paste` rather than `type` for long inputs.
- Wraps `Manager` component functions in `useCallback`.
- Replace deprecated `faker` helper.
=> test: improve performance

package.json, pnpm-lock.yaml
Upgrade `next-router-mock` to 0.9.6
=> deps: upgrade next-router-mock to 0.9.6

components/function/nonpayable/index.test.tsx, components/function/nonpayable/index.tsx, components/function/output/index.test.tsx, components/function/payable/index.test.tsx, components/function/payable/index.tsx, components/function/pure/index.test.tsx, components/function/view/index.test.tsx, components/wallet/account/index.test.tsx, components/wallet/account/index.tsx, components/wallet/transfer/index.tsx, core/types/index.ts, hooks/useArgs/index.test.tsx, hooks/useArgs/index.ts, hooks/useEther/index.test.tsx, hooks/useEther/index.ts, package.json, packages/core/connector/index.test.ts, packages/core/connector/index.ts, packages/core/wallet/index.ts, packages/wallets/index.ts, pages/_app.tsx, pnpm-lock.yaml, tsconfig.json
- Upgrade `wagmi` to 1.1.1
- Upgrade `@rainbow-me/rainbowkit` to 1.0.1
- Bump tsconfig target to `es2020` for bigint primitives
=> deps: upgrade wagmi to 1.1.1

package.json, pnpm-lock.yaml
- Upgrade `vitest` to 0.32.2
- Upgrade `@vitest/coverage-c8` to 0.32.2
- Replace `@vitest/coverage-c8` with `@vitest/coverage-v8`
=> deps: upgrade vitest to 0.32.2

package.json, pnpm-lock.yaml
Upgrade `next-router-mock` to 0.9.7
=> deps: upgrade next-router-mock to 0.9.7

package.json, pnpm-lock.yaml
- Upgrade `@typescript-eslint/eslint-plugin` to 5.60.1
- Upgrade `@typescript-eslint/parser` to 5.60.1
=> deps: upgrade @typescript-eslint to 5.60.1

package.json, pnpm-lock.yaml
- Upgrade `@typescript-eslint/eslint-plugin` to 5.61.0
- Upgrade `@typescript-eslint/parser` to 5.61.0
=> deps: upgrade @typescript-eslint to 5.61.0

package.json, pnpm-lock.yaml
- Upgrade `vite` to 4.4.2 
- Upgrade `vitest` to 0.33.0
- Upgrade `@vitest/coverage-v8` to 0.33.0
=> deps: upgrade vite to 4.4.2

package.json, pnpm-lock.yaml
- Upgrade `@typescript-eslint/eslint-plugin` to 6.1.0
- Upgrade `@typescript-eslint/parser` to 6.1.0
=> deps: upgrade @typescript-eslint to 6.1.0

package.json, pnpm-lock.yaml
Upgrade `eslint-config-prettier` to 8.9.0
=> deps: upgrade eslint-config-prettier to 8.9.0

package.json, pnpm-lock.yaml
- Upgrade `@typescript-eslint/eslint-plugin` to 6.2.0
- Upgrade `@typescript-eslint/parser` to 6.2.0
=> deps: upgrade @typescript-eslint to 6.2.0

package.json, pnpm-lock.yaml
- Upgrade `vitest` to 0.34.1
- Upgrade `vite` to 4.4.8
- Upgrade `@vitest/coverage-v8` to 0.34.1
=> deps: upgrade vitest to latest

package.json, pnpm-lock.yaml
Upgrade `eslint-config-prettier` to 9.0.0
=> deps: upgrade eslint-config-prettier to 9.0.0

package.json, pnpm-lock.yaml
Upgrade `node-mocks-http` to 1.13.0
=> deps: upgrade node-mocks-http to 1.13.0

package.json, pnpm-lock.yaml
Upgrade `next-router-mock` to 0.9.9
=> deps: upgrade next-router-mock to 0.9.9

package.json, pnpm-lock.yaml
Upgrade `whatwg-fetch` to 3.6.18
=> deps: upgrade whatwg-fetch to 3.6.18

package.json, pnpm-lock.yaml
- Upgrade `@typescript-eslint/eslint-plugin` to 6.6.0
- Upgrade `@typescript-eslint/parser` to 6.6.0
=> deps: upgrade @typescript-eslint to 6.6.0

package.json, pnpm-lock.yaml
Upgrade `@vitest/coverage-v8` to 0.34.4
=> deps: upgrade @vitest/coverage-v8 to 0.34.4

package.json, pnpm-lock.yaml
Upgrade `next-router-mock` to 0.9.10
=> deps: upgrade next-router-mock to 0.9.10

package.json, pnpm-lock.yaml
- Upgrade `@typescript-eslint/eslint-plugin` to 6.7.4
- Upgrade `@typescript-eslint/parser` to 6.7.4
=> deps: upgrade @typescript-eslint to 6.7.4

package.json, pnpm-lock.yaml
- Upgrade `@typescript-eslint/eslint-plugin` to 6.10.0
- Upgrade `@typescript-eslint/parser` to 6.10.0
=> deps: upgrade typescript-eslint to 6.10.0

package.json, pnpm-lock.yaml
Upgrade `tailwindcss` to 3.3.6
=> deps: upgrade tailwindcss to 3.3.6

package.json, pnpm-lock.yaml
- Upgrade `@vitest/coverage-v8` to 1.0.2
- Upgrade `vitest` to 1.0.2
=> deps: upgrade vitest to 1.0.2

package.json, pnpm-lock.yaml
Upgrade `eslint-config-prettier` to 9.1.0
=> deps: upgrade eslint-config-prettier to 9.1.0
