blacksmith-eth/blacksmith

package.json, yarn.lock
Upgrade @types/node to 18.11.11
=> deps: upgrade @types/node to 18.11.11

components/contracts/index.tsx
I love the idea and the look and feel of this web app. Great work!! 👏
This PR makes it easier to distinguish which contract is being hovered and which contract is focused by the mouse. I found that it was not very visible at first sight :)
I couldn't record a video unfortunately so the screenshots only show the contracts focused by the mouse. The app reacts in the same way when you move the mouse over any contract.
=> Update button hover and focus styles

package.json, yarn.lock
=> deps: upgrade prettier to 2.8.1

package.json, yarn.lock
Upgrade @types/node to 18.11.12
=> deps: upgrade @types/node to 18.11.12

pages/_document.tsx
now you can scroll only if hovering above the section with contract's UI
and there is no unintended scroll behavior.
=> fix scroll overflow issue #2

package.json, yarn.lock
Upgrade @headlessui/react to 1.7.5
=> deps: upgrade @headlessui/react to 1.7.5

components/wallet/account/index.test.tsx
Remove unused BlacksmithConnector import
=> refactor: remove unused blacksmith import

package.json, yarn.lock
Upgrade @types/node to 18.11.13
=> deps: upgrade @types/node to 18.11.13

.github/workflows/main.yml, package.json
Add main github actions workflow
=> ci: github actions

components/contract/manager/index.tsx, components/contract/setup/index.tsx
Set instruction paragraph max width to prose.
=> style: prose paragraph

.github/ISSUE_TEMPLATE/bug_report.md
=> docs: add bug report template

components/function/payable/index.tsx
Increase payable unit options z-index
=> fix: increase payable unit options z-index

components/inputs/index.tsx
Make nested input labels unique
=> fix: unique nested input labels

components/contract/manager/index.test.tsx, components/contract/manager/index.tsx
Render error on failed contract import
=> fix: render error on failed import

components/function/nonpayable/index.test.tsx, components/function/nonpayable/index.tsx, components/function/payable/index.test.tsx, components/function/payable/index.tsx, components/function/pure/index.test.tsx, components/function/view/index.test.tsx, hooks/useArgs/index.test.tsx, package.json, yarn.lock
=> deps: upgrade abitype to 0.1.8

package.json, yarn.lock
=> deps: upgrade postcss to 8.4.20

package.json, yarn.lock
=> deps: upgrade abitype to 0.2.5

components/function/nonpayable/index.tsx, components/function/output/index.test.tsx, components/function/output/index.tsx, components/function/payable/index.tsx, components/function/pure/index.tsx, components/function/view/index.tsx
=> feat: add prepare error message

testing/factory/index.ts
Exclude reserved words in test factory
=> test: exclude reserved words

components/function/payable/index.tsx, components/unit/index.tsx, components/wallet/transfer/index.tsx
=> refactor: unit selection

package.json, yarn.lock
Upgrade @types/node to 18.11.14
=> deps: upgrade @types/node to 18.11.14

package.json, yarn.lock
Upgrade @types/node to 18.11.15
=> deps: upgrade @types/node to 18.11.15

package.json, yarn.lock
Upgrade @rainbow-me/rainbowkit to 0.8.1
=> deps: upgrade @rainbow-me/rainbowkit to 0.8.1

components/balance/index.tsx, components/wallet/account/index.tsx, package.json, packages/core/connector/index.ts, pages/_app.tsx, yarn.lock
=> deps: upgrade wagmi to 0.9.2

package.json, yarn.lock
=> deps: upgrade wagmi to 0.9.3

components/contract/manager/index.test.tsx, components/contract/manager/index.tsx, core/utils/index.ts, pages/api/contracts/[address].ts, pages/api/verify.ts
Add contract address checksum to contract import, verify, remove, and view
=> feat: checksum contract address

package.json
Add format and lint fix scripts
=> chore: add fix scripts

components/function/nonpayable/index.tsx, components/function/payable/index.tsx
Replace ABI any type with const assertion
=> chore: replace abi any type with const assertion

package.json, yarn.lock
Upgrade `@headlessui/react` to 1.7.6
=> deps: upgrade @headlessui/react to 1.7.6

components/function/nonpayable/index.test.tsx, components/function/payable/index.test.tsx, components/function/pure/index.test.tsx, components/function/view/index.test.tsx
Remove unnecessary code
Remove `clearAllMocks` calls
=> test: remove unused cleanup

package.json, yarn.lock
=> deps: upgrade wagmi to 0.9.4

package.json, yarn.lock
Upgrade `@headlessui/react` to 1.7.7
=> deps: upgrade @headlessui/react to 1.7.7

package.json, yarn.lock
Upgrade `@types/node` to 18.11.16
=> deps: upgrade @types/node to 18.11.16

package.json, yarn.lock
=> deps: upgrade eslint to 8.30.0

components/footer/index.tsx, components/header/index.tsx, pages/index.tsx
Disparate page layout sections can be split into separate components.
Extract `Header` and `Footer` components from `Home`.
=> refactor: home

package.json, yarn.lock
Upgrade `@types/node` to 18.11.17
=> deps: upgrade @types/node to 18.11.17

__tests__/pages/api/contracts/[address].test.ts, pages/api/contracts/[address].ts
Improve test coverage for `api/contracts/[address].ts`
Add tests for `api/contracts/[address].ts`
=> test: backfill contracts address api assertions

__tests__/pages/api/contracts/index.test.ts
Improve test coverage for `api/contracts/index.ts`
Add tests for `api/contracts/index.ts`
=> test: backfill contracts api assertions

packages/core/wallet/index.test.ts
Improve test coverage for `packages/core/wallet`
Add tests for packages/core/wallet`
=> test: backfill wallet signer assertion

package.json, yarn.lock
Contributors should easily be able to obtain test coverage reporting.
- Add `@vitest/coverage-c8`
- Add test coverage script
=> feat: test coverage

package.json, yarn.lock
=> deps: upgrade wagmi to 0.9.5

package.json, yarn.lock
Upgrade `@vitest/coverage-c8` to 0.26.2
=> deps: upgrade @vitest/coverage-c8 to 0.26.2

package.json, yarn.lock
Peer dependency warnings are shown on `yarn install`.
Add `@babel/core` dependency.
=> deps: add @babel/core

package.json, yarn.lock
Upgrade `@types/node` to 18.11.18
=> deps: upgrade @types/node to 18.11.18

components/footer/index.tsx
The "report an issue" link should navigate to the issue template selection page.
Change "report an issue" link to navigate to the issue template selection page.
=> feat: update issue route to template choice

package.json, yarn.lock
=> deps: upgrade wagmi to 0.10.0

package.json, pages/api/contracts/[address].ts, yarn.lock
Improve runtime type checking.
- Add `zod`
- Parse `api/contracts/[address].ts` request params using `zod`
=> deps: add zod

.github/CONTRIBUTING.md
Project should include instructions for contributors.
Add `CONTRIBUTING.md` document.
=> docs: add contributing document

components/field/index.test.tsx, components/wallet/transfer/index.test.tsx, hooks/useArgs/index.test.tsx, hooks/useEther/index.test.tsx, testing/factory/index.ts
Avoid loading unused faker locale data into memory.
Specify faker locale on import.
=> test: specify faker locale

components/contract/index.test.tsx, components/contract/index.tsx, components/contract/setup/index.test.tsx, components/contract/setup/index.tsx, testing/index.tsx
Improve test coverage.
Backfill clipboard copy assertions.
=> test: backfill copy assertions

components/contracts/index.test.tsx
Improve test coverage.
Backfill active contract class assertion.
=> test: backfill active contract class assertion

package.json, yarn.lock
Upgrade `@vitest/coverage-c8` to 0.26.3
=> deps: upgrade @vitest/coverage-c8 to 0.26.3

package.json, yarn.lock
=> deps: upgrade husky to 8.0.3

package.json, yarn.lock
Upgrade `@babel/core` to 7.20.12
=> deps: upgrade @babel/core to 7.20.12

package.json, yarn.lock
=> deps: upgrade postcss to 8.4.21

package.json, yarn.lock
=> deps: upgrade prettier to 2.8.2

package.json, yarn.lock
=> deps: upgrade jsdom to 21.0.0

package.json, yarn.lock
Upgrade `@commitlint/cli` to 17.4.1
=> deps: upgrade @commitlint/cli to 17.4.1

package.json, yarn.lock
Upgrade `@vitest/coverage-c8` to 0.27.0
=> deps: upgrade @vitest/coverage-c8 to 0.27.0

yarn.lock
Keep transitive dependencies updated.
Update transitive dependencies.
=> deps: upgrade transitive dependencies to latest

package.json, yarn.lock
Upgrade `@vitest/coverage-c8` to 0.27.1
=> deps: upgrade @vitest/coverage-c8 to 0.27.1

components/contract/manager/index.tsx
Clarify existing contract import behavior.
Add instructions to _Contract Management_ section regarding current contract import limitations.
=> feat: clarify existing contract import behavior

package.json, yarn.lock
=> deps: upgrade prettier to 2.8.3

package.json, yarn.lock
=> deps: upgrade eslint to 8.32.0

package.json, yarn.lock
Upgrade `@types/react` to 18.0.27
=> deps: upgrade @types/react to 18.0.27

package.json, yarn.lock
=> deps: upgrade msw to 0.49.3

package.json, yarn.lock
=> deps: upgrade abitype to 0.3.0

package.json, pages/_app.tsx, tailwind.config.js, yarn.lock
The look and feel of Blacksmith should be consistent for users regardless of installed fonts, browser stylesheets, etc.
- Install `@next/font`
- Use Inter for `font-sans`
- Use Source Code Pro for `font-mono`
=> feat: add custom fonts

package.json, yarn.lock
=> deps: upgrade msw to 1.0.0

package.json, yarn.lock
Upgrade `@heroicons/react` to 2.0.14
=> deps: upgrade @heroicons/react to 2.0.14

package.json, yarn.lock
=> deps: upgrade lowdb to 5.1.0

package.json, yarn.lock
Upgrade `@vitejs/plugin-react` to 3.1.0
=> deps: upgrade @vitejs/plugin-react to 3.1.0

package.json, yarn.lock
Upgrade `@headlessui/react` to 1.7.9
=> deps: upgrade @headlessui/react to 1.7.9

package.json, yarn.lock
=> deps: upgrade wagmi to 0.11.4

__tests__/pages/api/verify.test.ts
Reduce duplication in verify tests.
Add verify assertion helpers.
=> test: add verify assertion helpers

package.json, yarn.lock
Upgrade `@types/node` to 18.11.19
=> deps: upgrade @types/node to 18.11.19

package.json, yarn.lock
Upgrade `@types/node` to 18.13.0
=> deps: upgrade @types/node to 18.13.0

package.json, yarn.lock
Upgrade `@heroicons/react` to 2.0.15
=> deps: upgrade @heroicons/react to 2.0.15

package.json, yarn.lock
=> deps: upgrade prettier to 2.8.4

package.json, yarn.lock
=> deps: upgrade zod to 3.20.5

package.json, yarn.lock
=> deps: upgrade wagmi to 0.11.5

package.json, yarn.lock
=> deps: upgrade abitype to 0.4.0

package.json, yarn.lock
=> deps: upgrade zod to 3.20.6

package.json, yarn.lock
=> deps: upgrade msw to 1.0.1

package.json, yarn.lock
Upgrade `@types/react` to 18.0.28
=> deps: upgrade @types/react to 18.0.28

package.json, yarn.lock
=> deps: upgrade abitype to 0.4.1

package.json, yarn.lock
=> deps: upgrade eslint to 8.34.0

package.json, yarn.lock
- Upgrade `@commitlint/cli` to 17.4.3
- Upgrade `@commitlint/config-conventional` to 17.4.3
=> deps: upgrade commitlint to 17.4.3

package.json, yarn.lock
Upgrade `@rainbow-me/rainbowkit` to 0.10.0
=> deps: upgrade @rainbow-me/rainbowkit to 0.10.0

package.json, yarn.lock
Upgrade `@headlessui/react` to 1.7.11
=> deps: upgrade @headlessui/react to 1.7.11

package.json, yarn.lock
Upgrade `@rainbow-me/rainbowkit` to 0.11.0
=> deps: upgrade @rainbow-me/rainbowkit to 0.11.0

package.json, yarn.lock
Upgrade `@testing-library/react` to 14.0.0
=> deps: upgrade @testing-library/react to 14.0.0

package.json, yarn.lock
Upgrade `@heroicons/react` to 2.0.16
=> deps: upgrade @heroicons/react to 2.0.16

package.json, yarn.lock
Upgrade `@types/node` to 18.14.0
=> deps: upgrade @types/node to 18.14.0

package.json, yarn.lock
- Upgrade `@commitlint/cli` to 17.4.4
- Upgrade `@commitlint/config-conventional` to 17.4.4
=> deps: upgrade commitlint to 17.4.4

package.json, yarn.lock
Upgrade `@babel/core` to 7.21.0
=> deps: upgrade @babel/core to 7.21.0

package.json, yarn.lock
=> deps: upgrade wagmi to 0.11.6

package.json, yarn.lock
=> deps: upgrade abitype to 0.5.0

package.json, yarn.lock
Upgrade `@types/node` to 18.14.1
=> deps: upgrade @types/node to 18.14.1

package.json, yarn.lock
=> deps: upgrade wagmi to 0.11.7

package.json, yarn.lock
=> deps: upgrade msw to 1.1.0

package.json, yarn.lock
Upgrade `@headlessui/react` to 1.7.12
=> deps: upgrade @headlessui/react to 1.7.12

package.json, yarn.lock
Upgrade `@types/node` to 18.14.2
=> deps: upgrade @types/node to 18.14.2

package.json, yarn.lock
=> deps: upgrade eslint to 8.35.0

package.json, yarn.lock
- Upgrade @typescript-eslint/eslint-plugin to 5.54.0
- Upgrade @typescript-eslint/parser to 5.54.0
=> deps: upgrade @typescript-eslint to 5.54.0

package.json, yarn.lock
=> deps: upgrade abitype to 0.6.1

package.json, yarn.lock
=> deps: upgrade abitype to 0.6.2

package.json, yarn.lock
Upgrade `@types/node` to 18.14.4
=> deps: upgrade @types/node to 18.14.4

package.json, yarn.lock
Upgrade `@types/node` to 18.14.5
=> deps: upgrade @types/node to 18.14.5

package.json, yarn.lock
Upgrade `@types/node` to 18.14.6
=> deps: upgrade @types/node to 18.14.6

package.json, yarn.lock
Upgrade `@headlessui/react` to 1.7.13
=> deps: upgrade @headlessui/react to 1.7.13

package.json, yarn.lock
Upgrade `@rainbow-me/rainbowkit` to 0.11.1
=> deps: upgrade @rainbow-me/rainbowkit to 0.11.1

package.json, yarn.lock
=> deps: upgrade zod to 3.21.0

package.json, yarn.lock
=> deps: upgrade abitype to 0.6.5

package.json, yarn.lock
=> deps: upgrade zod to 3.21.2

package.json, yarn.lock
Upgrade `eslint-config-prettier` to 8.7.0
=> deps: upgrade eslint-config-prettier to 8.7.0

package.json, yarn.lock
- Upgrade @typescript-eslint/eslint-plugin to 5.54.1
- Upgrade @typescript-eslint/parser to 5.54.1
=> deps: upgrade @typescript-eslint to 5.54.1

package.json, yarn.lock
=> deps: upgrade abitype to 0.6.7

package.json, yarn.lock
=> deps: upgrade zod to 3.21.3

package.json, yarn.lock
=> deps: upgrade zod to 3.21.4

package.json, yarn.lock
=> deps: upgrade wagmi to 0.12.1

package.json, yarn.lock
=> deps: upgrade abitype to 0.6.8

package.json, vite.config.ts, yarn.lock
Prefer `swc` over `babel`.
- Add `@vitejs/plugin-react-swc`
- Remove `@vitejs/plugin-react`
=> deps: add @vitejs/plugin-react-swc

package.json, yarn.lock
Upgrade `@rainbow-me/rainbowkit` to 0.12.0
=> deps: upgrade @rainbow-me/rainbowkit to 0.12.0

package.json, yarn.lock
Upgrade `@types/node` to 18.15.0
=> deps: upgrade @types/node to 18.15.0

package.json, yarn.lock
Upgrade `autoprefixer` to 10.4.14
=> deps: upgrade autoprefixer to 10.4.14

package.json, yarn.lock
Upgrade `@types/node` to 18.15.3
=> deps: upgrade @types/node to 18.15.3

package.json, yarn.lock
Upgrade `@babel/core` to 7.21.3
=> deps: upgrade @babel/core to 7.21.3

package.json, yarn.lock
=> deps: upgrade jsdom to 21.1.1

package.json, yarn.lock
Upgrade `@rainbow-me/rainbowkit` to 0.12.1
=> deps: upgrade @rainbow-me/rainbowkit to 0.12.1

package.json, yarn.lock
- Upgrade @typescript-eslint/eslint-plugin to 5.55.0
- Upgrade @typescript-eslint/parser to 5.55.0
=> deps: upgrade @typescript-eslint to 5.55.0

package.json, yarn.lock
=> deps: upgrade abitype to 0.7.1

package.json, yarn.lock
=> deps: upgrade wagmi to 0.12.2

package.json, yarn.lock
Upgrade `@types/node` to 18.15.5
=> deps: upgrade @types/node to 18.15.5

package.json, yarn.lock
=> deps: upgrade prettier to 2.8.6

package.json, yarn.lock
=> deps: upgrade wagmi to 0.12.6

package.json, yarn.lock
=> deps: upgrade msw to 1.2.1

package.json, yarn.lock
Upgrade `@types/node` to 18.15.7
=> deps: upgrade @types/node to 18.15.7

package.json, yarn.lock
=> deps: upgrade prettier to 2.8.7

package.json, yarn.lock
Upgrade `eslint-config-prettier` to 8.8.0
=> deps: upgrade eslint-config-prettier to 8.8.0

package.json, yarn.lock
Upgrade `@commitlint/cli` to 17.5.0
=> deps: upgrade @commitlint/cli to 17.5.0

package.json, yarn.lock
Upgrade `@types/react` to 18.0.29
=> deps: upgrade @types/react to 18.0.29

package.json, yarn.lock
Upgrade `@rainbow-me/rainbowkit` to 0.12.4
=> deps: upgrade @rainbow-me/rainbowkit to 0.12.4

package.json, yarn.lock
Upgrade `zod-validation-error` to 1.1.0
=> deps: upgrade zod-validation-error to 1.1.0

package.json, yarn.lock
Upgrade `@types/node` to 18.15.8
=> deps: upgrade @types/node to 18.15.8

package.json, yarn.lock
Upgrade `@types/node` to 18.15.9
=> deps: upgrade @types/node to 18.15.9

package.json, yarn.lock
Upgrade `@types/node` to 18.15.10
=> deps: upgrade @types/node to 18.15.10

package.json, yarn.lock
Upgrade `@commitlint/cli` to 17.5.1
=> deps: upgrade @commitlint/cli to 17.5.1

package.json, yarn.lock
Upgrade `@types/lodash` to 4.14.192
=> deps: upgrade @types/lodash to 4.14.192

package.json, yarn.lock
Upgrade `@babel/core` to 7.21.4
=> deps: upgrade @babel/core to 7.21.4

package.json, yarn.lock
Upgrade `@heroicons/react` to 2.0.17
=> deps: upgrade @heroicons/react to 2.0.17

package.json, yarn.lock
Upgrade `@types/react` to 18.0.31
=> deps: upgrade @types/react to 18.0.31

package.json, yarn.lock
=> deps: upgrade typescript to 5.0.3

package.json, yarn.lock
Upgrade `@rainbow-me/rainbowkit` to 0.12.5
=> deps: upgrade @rainbow-me/rainbowkit to 0.12.5

package.json, yarn.lock
=> deps: upgrade eslint to 8.37.0

package.json, yarn.lock
=> deps: upgrade wagmi to 0.12.8

package.json, yarn.lock
Upgrade `tailwindcss` to 3.3.1
=> deps: upgrade tailwindcss to 3.3.1

package.json, yarn.lock
Upgrade `@types/react` to 18.0.32
=> deps: upgrade @types/react to 18.0.32

package.json, yarn.lock
Upgrade `@types/react` to 18.0.33
=> deps: upgrade @types/react to 18.0.33

package.json, yarn.lock
=> deps: upgrade wagmi to 0.12.9

package.json, yarn.lock
=> deps: upgrade typescript to 5.0.4

package.json, yarn.lock
=> deps: upgrade wagmi to 0.12.10

package.json, yarn.lock
Upgrade `@rainbow-me/rainbowkit` to 0.12.7
=> deps: upgrade @rainbow-me/rainbowkit to 0.12.7

package.json, yarn.lock
Upgrade `zod-validation-error` to 1.3.0
=> deps: upgrade zod-validation-error to 1.3.0

package.json
Add single script for running continuous integration tasks.
Add `ci` script to `package.json`.
=> chore: add ci script

package.json, yarn.lock
Upgrade `@types/react` to 18.0.34
=> deps: upgrade @types/react to 18.0.34

package.json, yarn.lock
Upgrade `@types/react` to 18.0.35
=> deps: upgrade @types/react to 18.0.35

package.json, yarn.lock
Upgrade `@headlessui/react` to 1.7.14
=> deps: upgrade @headlessui/react to 1.7.14

package.json, yarn.lock
Upgrade `@types/lodash` to 4.14.194
=> deps: upgrade @types/lodash to 4.14.194

package.json, yarn.lock
Upgrade `@rainbow-me/rainbowkit` to 0.12.8
=> deps: upgrade @rainbow-me/rainbowkit to 0.12.8

package.json, yarn.lock
Upgrade `@commitlint/cli` to 17.6.1
=> deps: upgrade @commitlint/cli to 17.6.1

package.json, yarn.lock
=> deps: upgrade postcss to 8.4.22

package.json, yarn.lock
Upgrade `@types/node` to 18.15.12
=> deps: upgrade @types/node to 18.15.12

package.json, yarn.lock
=> deps: upgrade postcss to 8.4.23

package.json, yarn.lock
Upgrade `@types/node` to 18.15.13
=> deps: upgrade @types/node to 18.15.13

package.json, yarn.lock
Upgrade `@types/react` to 18.0.38
=> deps: upgrade @types/react to 18.0.38

package.json, yarn.lock
=> deps: upgrade wagmi to 0.12.12

package.json, yarn.lock
Upgrade `@rainbow-me/rainbowkit` to 0.12.9
=> deps: upgrade @rainbow-me/rainbowkit to 0.12.9

package.json, yarn.lock
=> deps: upgrade eslint to 8.39.0

package.json, yarn.lock
=> deps: upgrade abitype to 0.8.0

package.json, yarn.lock
=> deps: upgrade fp-ts to 2.14.0

package.json, yarn.lock
Upgrade `@vitejs/plugin-react-swc` to 3.3.0
=> deps: upgrade @vitejs/plugin-react-swc to 3.3.0

package.json, yarn.lock
=> deps: upgrade prettier to 2.8.8

package.json, yarn.lock
Upgrade `@types/node` to 18.16.0
=> deps: upgrade @types/node to 18.16.0

package.json, yarn.lock
Upgrade `@babel/core` to 7.21.5
=> deps: upgrade @babel/core to 7.21.5

package.json, yarn.lock
Upgrade `@types/node` to 18.16.3
=> deps: upgrade @types/node to 18.16.3

package.json, yarn.lock
Upgrade `@types/react` to 18.2.0
=> deps: upgrade @types/react to 18.2.0

package.json, yarn.lock
=> deps: upgrade jsdom to 21.1.2

package.json, yarn.lock
Upgrade `@babel/core` to 7.21.8
=> deps: upgrade @babel/core to 7.21.8

package.json, yarn.lock
=> deps: upgrade abitype to 0.8.2

package.json, yarn.lock
=> deps: upgrade wagmi to 0.12.13

package.json, yarn.lock
Upgrade `@rainbow-me/rainbowkit` to 0.12.12
=> deps: upgrade @rainbow-me/rainbowkit to 0.12.12

package.json, yarn.lock
=> deps: upgrade eslint to 8.40.0

package.json, yarn.lock
=> deps: upgrade abitype to 0.8.3

package.json, yarn.lock
=> deps: upgrade fp-ts to 2.15.0

package.json, yarn.lock
Upgrade `@types/node` to 20.1.4
=> deps: upgrade @types/node to 20.1.4

package.json, yarn.lock
=> deps: upgrade jsdom to 22.0.0

package.json, yarn.lock
Upgrade `@types/node` to 20.1.7
=> deps: upgrade @types/node to 20.1.7

package.json, yarn.lock
=> deps: upgrade abitype to 0.8.4

package.json, yarn.lock
Upgrade `@types/node` to 20.2.1
=> deps: upgrade @types/node to 20.2.1

package.json, yarn.lock
=> deps: upgrade eslint to 8.41.0

package.json, yarn.lock
Upgrade `@types/node` to 20.2.3
=> deps: upgrade @types/node to 20.2.3

package.json, yarn.lock
Upgrade `@babel/core` to 7.22.1
=> deps: upgrade @babel/core to 7.22.1

package.json, yarn.lock
=> deps: upgrade fp-ts to 2.16.0

package.json, yarn.lock
=> deps: upgrade jsdom to 22.1.0

package.json, yarn.lock
Upgrade `@types/node` to 20.2.5
=> deps: upgrade @types/node to 20.2.5

package.json, yarn.lock
Upgrade `@vitejs/plugin-react-swc` to 3.3.1
=> deps: upgrade @vitejs/plugin-react-swc to 3.3.1

package.json, yarn.lock
=> deps: upgrade postcss to 8.4.24

package.json, yarn.lock
=> deps: upgrade abitype to 0.8.6

package.json, yarn.lock
- Upgrade `@commitlint/cli` to 17.6.5
- Upgrade `@commitlint/config-conventional` to 17.6.5
=> deps: upgrade @commitlint to 17.6.5

package.json, yarn.lock
Upgrade `@headlessui/react` to 1.7.15
=> deps: upgrade @headlessui/react to 1.7.15

README.md
Resolves #369
Add documentation to clarify the Etherscan verification requirement for imported contracts.
=> docs: add etherscan verification disclaimer

package.json, yarn.lock
=> deps: upgrade abitype to 0.8.7

package.json, yarn.lock
=> deps: upgrade eslint to 8.42.0

package.json, yarn.lock
Upgrade `@types/react` to 18.2.8
=> deps: upgrade @types/react to 18.2.8

package.json, yarn.lock
Upgrade `@rainbow-me/rainbowkit` to 0.12.14
=> deps: upgrade @rainbow-me/rainbowkit to 0.12.14

package.json, yarn.lock
Upgrade `@vitejs/plugin-react-swc` to 3.3.2
=> deps: upgrade @vitejs/plugin-react-swc to 3.3.2

package.json, pnpm-lock.yaml
- Upgrade `@typescript-eslint/eslint-plugin` to 5.59.9
- Upgrade `@typescript-eslint/parser` to 5.59.9
=> deps: upgrade @typescript-eslint to 5.59.9

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.3.0
=> deps: upgrade @types/node to 20.3.0

package.json, pnpm-lock.yaml
Upgrade `@babel/core` to 7.22.5
=> deps: upgrade @babel/core to 7.22.5

package.json, pnpm-lock.yaml
Upgrade `@types/react` to 18.2.11
=> deps: upgrade @types/react to 18.2.11

package.json, pnpm-lock.yaml
=> deps: upgrade abitype to 0.8.8

package.json, pnpm-lock.yaml
=> deps: upgrade msw to 1.2.2

package.json, pnpm-lock.yaml
Upgrade `@types/react` to 18.2.12
=> deps: upgrade @types/react to 18.2.12

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.3.1
=> deps: upgrade @types/node to 20.3.1

package.json, pnpm-lock.yaml
Upgrade `@rainbow-me/rainbowkit` to 1.0.2
=> deps: upgrade @rainbow-me/rainbowkit to 1.0.2

package.json, pnpm-lock.yaml
=> deps: upgrade abitype to 0.8.9

package.json, pnpm-lock.yaml
=> deps: upgrade wagmi to 1.2.0

package.json, pnpm-lock.yaml
=> deps: upgrade abitype to 0.8.10

package.json, pnpm-lock.yaml
=> deps: upgrade eslint to 8.43.0

package.json, pnpm-lock.yaml
- Upgrade @typescript-eslint/eslint-plugin to 5.59.11
- Upgrade @typescript-eslint/parser to 5.59.11
=> deps: upgrade @typescript-eslint to 5.59.11

package.json, pnpm-lock.yaml
Upgrade `@types/react` to 18.2.13
=> deps: upgrade @types/react to 18.2.13

package.json, pnpm-lock.yaml
Upgrade `zod-validation-error` to 1.3.1
=> deps: upgrade zod-validation-error to 1.3.1

package.json, pnpm-lock.yaml
=> deps: upgrade abitype to 0.8.11

package.json, pnpm-lock.yaml
=> deps: upgrade typescript to 5.1.6

package.json, pnpm-lock.yaml
=> deps: upgrade eslint to 8.44.0

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.3.3
=> deps: upgrade @types/node to 20.3.3

package.json, pnpm-lock.yaml
Upgrade `@rainbow-me/rainbowkit` to 1.0.4
=> deps: upgrade @rainbow-me/rainbowkit to 1.0.4

package.json, pnpm-lock.yaml
=> deps: upgrade wagmi to 1.3.3

package.json, pnpm-lock.yaml
Upgrade `@types/react` to 18.2.14
=> deps: upgrade @types/react to 18.2.14

package.json, pnpm-lock.yaml
- Upgrade `@commitlint/cli` to 17.6.6
- Upgrade `@commitlint/config-conventional` to 17.6.6
=> deps: upgrade @commitlint to 17.6.6

package.json, pnpm-lock.yaml
=> deps: upgrade abitype to 0.9.0

package.json, pnpm-lock.yaml
=> deps: upgrade wagmi to 1.3.5

package.json, pnpm-lock.yaml
Upgrade `@babel/core` to 7.22.6
=> deps: upgrade @babel/core to 7.22.6

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.4.0
=> deps: upgrade @types/node to 20.4.0

package.json, pnpm-lock.yaml
=> deps: upgrade postcss to 8.4.25

package.json, pnpm-lock.yaml
Upgrade `@babel/core` to 7.22.8
=> deps: upgrade @babel/core to 7.22.8

package.json, pnpm-lock.yaml
Upgrade `@rainbow-me/rainbowkit` to 1.0.5
=> deps: upgrade @rainbow-me/rainbowkit to 1.0.5

package.json, pnpm-lock.yaml
=> deps: upgrade wagmi to 1.3.8

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.4.1
=> deps: upgrade @types/node to 20.4.1

package.json, pnpm-lock.yaml
Upgrade `@typescript-eslint/eslint-plugin` to 6.0.0
Upgrade `@typescript-eslint/parser` to 6.0.0
=> deps: upgrade @typescript-eslint to 6.0.0

package.json, pnpm-lock.yaml
=> deps: upgrade abitype to 0.9.2

package.json, pnpm-lock.yaml
Upgrade `@babel/core` to 7.22.9
=> deps: upgrade @babel/core to 7.22.9

package.json, pnpm-lock.yaml
=> deps: upgrade eslint to 8.45.0

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.4.2
=> deps: upgrade @types/node to 20.4.2

package.json, pnpm-lock.yaml
Upgrade `@types/react` to 18.2.15
=> deps: upgrade @types/react to 18.2.15

package.json, pnpm-lock.yaml
=> deps: upgrade postcss to 8.4.26

package.json, pnpm-lock.yaml
Upgrade `tailwindcss` to 3.3.3
=> deps: upgrade tailwindcss to 3.3.3

package.json, pnpm-lock.yaml
Upgrade `@rainbow-me/rainbowkit` to 1.0.6
=> deps: upgrade @rainbow-me/rainbowkit to 1.0.6

package.json, pnpm-lock.yaml
=> deps: upgrade wagmi to 1.3.9

package.json, pnpm-lock.yaml
=> deps: upgrade vite to 4.4.4

package.json, pnpm-lock.yaml
=> deps: upgrade abitype to 0.9.3

package.json, pnpm-lock.yaml
Upgrade `@rainbow-me/rainbowkit` to 1.0.7
=> deps: upgrade @rainbow-me/rainbowkit to 1.0.7

package.json, pnpm-lock.yaml
=> deps: upgrade postcss to 8.4.27

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.4.3
=> deps: upgrade @types/node to 20.4.3

package.json, pnpm-lock.yaml
Upgrade `whatwg-fetch` to 3.6.17
=> deps: upgrade whatwg-fetch to 3.6.17

package.json, pnpm-lock.yaml
=> deps: upgrade msw to 1.2.3

package.json, pnpm-lock.yaml
=> deps: upgrade vite to 4.4.6

package.json, pnpm-lock.yaml
Upgrade `@testing-library/jest-dom` to 5.17.0
=> deps: upgrade @testing-library/jest-dom to 5.17.0

package.json, pnpm-lock.yaml
=> deps: upgrade abitype to 0.9.5

package.json, pnpm-lock.yaml
Upgrade `@types/lodash` to 4.14.196
=> deps: upgrade @types/lodash to 4.14.196

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.4.5
=> deps: upgrade @types/node to 20.4.5

package.json, pnpm-lock.yaml
Upgrade `@headlessui/react` to 1.7.16
=> deps: upgrade @headlessui/react to 1.7.16

package.json, pnpm-lock.yaml
Upgrade `@types/react` to 18.2.17
=> deps: upgrade @types/react to 18.2.17

package.json, pnpm-lock.yaml
=> deps: upgrade fp-ts to 2.16.1

package.json, pnpm-lock.yaml
=> deps: upgrade abitype to 0.9.6

package.json, pnpm-lock.yaml
=> deps: upgrade vite to 4.4.7

package.json, pnpm-lock.yaml
=> deps: upgrade eslint to 8.46.0

package.json, pnpm-lock.yaml
- Upgrade `@commitlint/cli` to 17.6.7
- Upgrade `@commitlint/config-conventional` to 17.6.7
=> deps: upgrade @commitlint to 17.6.7

package.json, pnpm-lock.yaml
Upgrade `@types/react` to 18.2.18
=> deps: upgrade @types/react to 18.2.18

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.4.6
=> deps: upgrade @types/node to 20.4.6

package.json, pnpm-lock.yaml
Upgrade `@rainbow-me/rainbowkit` to 1.0.8
=> deps: upgrade @rainbow-me/rainbowkit to 1.0.8

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.4.8
=> deps: upgrade @types/node to 20.4.8

package.json, pnpm-lock.yaml
=> deps: upgrade prettier to 3.0.1

package.json, pnpm-lock.yaml
Upgrade `@babel/core` to 7.22.10
=> deps: upgrade @babel/core to 7.22.10

package.json, pnpm-lock.yaml
Upgrade `@types/lodash` to 4.14.197
=> deps: upgrade @types/lodash to 4.14.197

package.json, pnpm-lock.yaml
=> deps: upgrade wagmi to 1.3.10

package.json, pnpm-lock.yaml
Upgrade `@types/react` to 18.2.20
=> deps: upgrade @types/react to 18.2.20

package.json, pnpm-lock.yaml
Upgrade `autoprefixer` to 10.4.15
=> deps: upgrade autoprefixer to 10.4.15

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.5.0
=> deps: upgrade @types/node to 20.5.0

package.json, pnpm-lock.yaml
=> deps: upgrade eslint to 8.47.0

package.json, pnpm-lock.yaml
=> deps: upgrade postcss to 8.4.28

package.json, pnpm-lock.yaml
=> deps: ugprade prettier to 3.0.2

package.json, pnpm-lock.yaml
Upgrade `@headlessui/react` to 1.7.17
=> deps: upgrade @headlessui/react to 1.7.17

package.json, pnpm-lock.yaml
=> deps: upgrade abitype to 0.9.8

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.5.1
=> deps: upgrade @types/node to 20.5.1

package.json, pnpm-lock.yaml
Upgrade `@rainbow-me/rainbowkit` to 1.0.9
=> deps: upgrade @rainbow-me/rainbowkit to 1.0.9

package.json, pnpm-lock.yaml
Upgrade `@babel/core` to 7.22.11
=> deps: upgrade @babel/core to 7.22.11

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.5.6
=> deps: upgrade @types/node to 20.5.6

package.json, pnpm-lock.yaml
Upgrade `@types/react` to 18.2.21
=> deps: upgrade @types/react to 18.2.21

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.5.7
=> deps: ugrade @types/node to 20.5.7

package.json, pnpm-lock.yaml
=> deps: upgrade postcss to 8.4.29

package.json, pnpm-lock.yaml
=> deps: upgrade msw to 1.2.5

package.json, pnpm-lock.yaml
=> deps: upgrade prettier to 3.0.3

package.json, pnpm-lock.yaml
Upgrade `@babel/core` to 7.22.15
=> deps: upgrade @babel/core to 7.22.15

package.json, pnpm-lock.yaml
Upgrade `@types/lodash` to 4.14.198
=> deps: upgrade @types/lodash to 4.14.198

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.5.9
=> deps: upgrade @types/node to 20.5.9

package.json, pnpm-lock.yaml
Upgrade `@babel/core` to 7.22.17
=> deps: upgrade @babel/core to 7.22.17

package.json, pnpm-lock.yaml
=> deps: upgrade eslint to 8.49.0

package.json, pnpm-lock.yaml
=> deps: upgrade msw to 1.3.0

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.6.0
=> deps: upgrade @types/node to 20.6.0

package.json, pnpm-lock.yaml
=> deps: upgrade typescript to 5.2.2

package.json, pnpm-lock.yaml
Upgrade `@rainbow-me/rainbowkit` to 1.0.11
=> deps: upgrade @rainbow-me/rainbowkit to 1.0.11

package.json, pnpm-lock.yaml
=> deps: upgrade wagmi to 1.4.1

package.json, pnpm-lock.yaml
Upgrade `@testing-library/jest-dom` to 6.1.3
=> deps: upgrade @testing-library/jest-dom to 6.1.3

package.json, pnpm-lock.yaml
=> deps: upgrade zod to 3.22.2

package.json, pnpm-lock.yaml
Upgrade `zod-validation-error` to 1.5.0
=> deps: upgrade zod-validation-error to 1.5.0

package.json, pnpm-lock.yaml
=> deps: upgrade vite to 4.4.9

package.json, pnpm-lock.yaml
=> deps: upgrade vitest to 0.34.4

package.json, pnpm-lock.yaml
Upgrade `vite-tsconfig-paths` to 4.2.1
=> deps: upgrade vite-tsconfig-paths to 4.2.1

package.json, pnpm-lock.yaml
Upgrade `@commitlint/cli` to 17.7.1
=> deps: upgrade @commitlint/cli to 17.7.1

package.json, pnpm-lock.yaml
Upgrade `@commitlint/config-conventional` to 17.7.0
=> deps: upgrade config-conventional to 17.7.0

package.json, pnpm-lock.yaml
Upgrade `whatwg-fetch` to 3.6.19
=> deps: upgrade whatwg-fetch to 3.6.19

package.json, pnpm-lock.yaml
Upgrade `@babel/core` to 7.22.19
=> deps: upgrade @babel/core to 7.22.19

package.json, pnpm-lock.yaml
Upgrade `@babel/core` to 7.22.20
=> deps: upgrade @babel/core to 7.22.20

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.6.3
=> deps: upgrade @types/node to 20.6.3

package.json, pnpm-lock.yaml
=> deps: upgrade msw to 1.3.1

package.json, pnpm-lock.yaml
=> deps: upgrade postcss to 8.4.30

package.json, pnpm-lock.yaml
Upgrade `autoprefixer` to 10.4.16
=> deps: upgrade autoprefixer to 10.4.16

package.json, pnpm-lock.yaml
=> deps: upgrade eslint to 8.50.0

package.json, pnpm-lock.yaml
Upgrade `@types/lodash` to 4.14.199
=> deps: upgrade @types/lodash to 4.14.199

package.json, pnpm-lock.yaml
=> deps: upgrade msw to 1.3.2

package.json, pnpm-lock.yaml
=> deps: upgrade postcss to 8.4.31

package.json, pnpm-lock.yaml
=> deps: upgrade abitype to 0.9.9

package.json, pnpm-lock.yaml
Upgrade `@types/react` to 18.2.25
=> deps: upgrade @types/react to 18.2.25

package.json, pnpm-lock.yaml
=> deps: upgrade vite to 4.4.11

package.json, pnpm-lock.yaml
=> deps: upgrade vitest to 0.34.6

package.json, pnpm-lock.yaml
Upgrade `@babel/core` to 7.23.0
=> deps: upgrade @babel/core to 7.23.0

package.json, pnpm-lock.yaml
=> deps: upgrade zod to 3.22.4

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.8.3
=> deps: upgrade @types/node to 20.8.3

package.json, pnpm-lock.yaml
=> deps: upgrade eslint to 8.51.0

package.json, pnpm-lock.yaml
Upgrade `@vitest/coverage-v8` to 0.34.6
=> deps: upgrade @vitest/coverage-v8 to 0.34.6

package.json, pnpm-lock.yaml
Upgrade `@vitejs/plugin-react-swc` to 3.4.0
=> deps: upgrade @vitejs/plugin-react-swc to 3.4.0

package.json, pnpm-lock.yaml
Upgrade `@testing-library/user-event` to 14.5.1
=> deps: upgrade user-event to 14.5.1

package.json, pnpm-lock.yaml
Upgrade `@commitlint/cli` to 17.7.2
=> deps: upgrade @commitlint/cli to 17.7.2

package.json, pnpm-lock.yaml
Upgrade `@faker-js/faker` to 8.1.0
=> deps: upgrade @faker-js/faker to 8.1.0

package.json, pnpm-lock.yaml
=> deps: upgrade wagmi to 1.4.3

package.json, pnpm-lock.yaml
Upgrade `@rainbow-me/rainbowkit` to 1.1.1
=> deps: upgrade @rainbow-me/rainbowkit to 1.1.1

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.8.4
=> deps: upgrade @types/node to 20.8.4

package.json, pnpm-lock.yaml
Upgrade `@babel/core` to 7.23.2
=> deps: upgrade @babel/core to 7.23.2

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.8.6
=> deps: upgrade @types/node to 20.8.6

package.json, pnpm-lock.yaml
Upgrade `@types/lodash` to 4.14.200
=> deps: upgrade @types/lodash to 4.14.200

package.json, pnpm-lock.yaml
=> deps: upgrade abitype to 0.10.1

package.json, pnpm-lock.yaml
Upgrade `tailwindcss` to 3.3.4
=> deps: upgrade tailwindcss to 3.3.4

package.json, pnpm-lock.yaml
Upgrade `tailwindcss` to 3.3.5
=> deps: upgrade tailwindcss to 3.3.5

package.json, pnpm-lock.yaml
=> deps: upgrade abitype to 0.10.2

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.8.10
=> deps: upgrade @types/node to 20.8.10

package.json, pnpm-lock.yaml
=> deps: upgrade eslint to 8.52.0

package.json, pnpm-lock.yaml
Upgrade `@faker-js/faker` to 8.2.0
=> deps: upgrade @faker-js/faker to 8.2.0

package.json, pnpm-lock.yaml
Upgrade `@testing-library/jest-dom` to 6.1.4
=> deps: upgrade @testing-library/jest-dom to 6.1.4

package.json, pnpm-lock.yaml
Upgrade `@babel/core` to 7.23.3
=> deps: upgrade @babel/core to 7.23.3

package.json, pnpm-lock.yaml
Upgrade `@types/lodash` to 4.14.201
=> deps: upgrade @types/lodash to 4.14.201

package.json, pnpm-lock.yaml
Upgrade `@types/react` to 18.2.37
=> deps: upgrade @types/react to 18.2.37

package.json, pnpm-lock.yaml
=> deps: upgrade vite to 4.5.0

package.json, pnpm-lock.yaml
Upgrade `@vitejs/plugin-react-swc` to 3.4.1
=> deps: upgrade @vitejs/plugin-react-swc to 3.4.1

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.9.0
=> deps: upgrade @types/node to 20.9.0

package.json, pnpm-lock.yaml
Upgrade `@testing-library/react` to 14.1.0
=> deps: upgrade @testing-library/react to 14.1.0

package.json, pnpm-lock.yaml
=> deps: upgrade eslint to 8.53.0

package.json, pnpm-lock.yaml
Upgrade `zod-validation-error` to 2.1.0
=> deps: upgrade zod-validation-error to 2.1.0

package.json, pnpm-lock.yaml
=> deps: upgrade wagmi to 1.4.6

package.json, pnpm-lock.yaml
Upgrade `@rainbow-me/rainbowkit` to 1.2.0
=> deps: upgrade @rainbow-me/rainbowkit to 1.2.0

package.json, pnpm-lock.yaml
- Upgrade `@commitlint/cli` to 18.4.1
- Upgrade `@commitlint/config-conventional` to 18.4.0
=> deps: upgrade commitlint to 18.4.x

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.9.2
=> deps: upgrade @types/node to 20.9.2

package.json, pnpm-lock.yaml
Upgrade `@types/lodash` to 4.14.202
=> deps: upgrade @types/lodash to 4.14.202

package.json, pnpm-lock.yaml
Upgrade `@babel/core` to 7.23.5
=> deps: upgrade @babel/core to 7.23.5

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.10.2
=> deps: upgrade @types/node to 20.10.2

package.json, pnpm-lock.yaml
Upgrade `@types/node` to 20.10.4
=> deps: upgrade @types/node to 20.10.4

package.json, pnpm-lock.yaml
- Upgrade `@commitlint/cli` to 18.4.3
- Upgrade `@commitlint/config-conventional` to 18.4.3
=> deps: upgrade commitlint to 18.4.3

package.json, pnpm-lock.yaml
=> deps: upgrade eslint to 8.55.0

package.json, pnpm-lock.yaml
=> deps: upgrade prettier to 3.1.0

package.json, pnpm-lock.yaml
Upgrade `@testing-library/jest-dom` to 6.1.5
=> deps: upgrade @testing-library/jest-dom to 6.1.5

package.json, pnpm-lock.yaml
Upgrade `@testing-library/react` to 14.1.2
=> deps: upgrade @testing-library/react to 14.1.2

package.json, pnpm-lock.yaml
=> deps: upgrade vite to 5.0.7

package.json, pnpm-lock.yaml
Upgrade `vite-tsconfig-paths` to 4.2.2
=> deps: upgrade vite-tsconfig-paths to 4.2.2

package.json, pnpm-lock.yaml
Upgrade `@faker-js/faker` to 8.3.1
=> deps: upgrade @faker-js/faker to 8.3.1

package.json, pnpm-lock.yaml
=> deps: upgrade wagmi to 1.4.10

package.json, pnpm-lock.yaml
Upgrade `@rainbow-me/rainbowkit` to 1.3.0
=> deps: upgrade @rainbow-me/rainbowkit to 1.3.0
